plugins {
    id("java")
    id("com.gradleup.shadow") version "9.4.1" apply false
}

allprojects {
    group = "io.github.jack1424"
    version = "2.0.0-DEV"

    repositories {
        mavenCentral()
        maven {
            name = "aikar-repo"
            url = "https://repo.aikar.co/nexus/content/groups/aikar/"
        }
        maven {
            name = "placeholderapi-repo"
            url = "https://repo.helpch.at/releases"
        }
        maven {
            name = "papermc-repo"
            url = uri("https://repo.papermc.io/repository/maven-public/")
        }
    }
}
