plugins {
    id("java")
    id("com.gradleup.shadow") version "8.3.10" apply false
}

allprojects {
    group = "io.github.jack1424"
    version = "2.0.0-DEV"

    repositories {
        mavenCentral()
        maven {
            name = "aikar-repo"
            url = "https://repo.aikar.co/nexus/content/groups/aikar/"
        }
        maven {
            name = "placeholderapi-repo"
            url = "https://repo.helpch.at/releases"
        }
    }
}

subprojects {
    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release.set(8)
    }
}
