# RealTimeWeather Configuration File (v2)
# You can find detailed instructions at: https://github.com/Jack1424/RealTimeWeather/wiki#editing-the-configuration-file

################################# TIME SYNC SETTINGS #################################################################
# Set to true to enable time syncing, or false to disable                                                            #
SyncTime: false
#                                                                                                                    #
# Set to false to enable the /time set command (not recommended)                                                     #
BlockTimeSetCommand: true
#                                                                                                                    #
# You can change the time between time syncs from the default (5 seconds) below                                      #
TimeSyncInterval: 100
#                                                                                                                    #
# Enter the time zone that you want to sync your world(s) with                                                       #
# This location CAN be different from your chosen weather location                                                   #
# You can find a full list of timezones here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List      #
Timezone: 'Etc/UTC'
#                                                                                                                    #
######################################################################################################################

################################# WEATHER SYNC SETTINGS ##############################################################
# Set to true to enable weather syncing, or false to disable                                                         #
SyncWeather: false
#                                                                                                                    #
# Set to false to enable the /weather command (not recommended)                                                      #
BlockWeatherCommand: true
#                                                                                                                    #
# You can change the time between weather syncs from the default (5 minutes) below                                   #
# Due to OpenWeather's restrictions, setting this value below 2400 (2 minutes) will cause problems                   #
# You can find a handy tick calculator here: https://mapmaking.fr/tick/                                              #
WeatherSyncInterval: 6000
#                                                                                                                    #
# In order to access the weather sync feature, create an account at https://openweathermap.org/                      #
# Then, create an API key at https://openweathermap.org/appid and copy it                                            #
# Finally, paste the API key below and DO NOT SHARE IT WITH OTHERS                                                   #
APIKey: 'API_KEY'
#                                                                                                                    #
# Enter the latitude and longitude of the location that you want to sync your world(s) weather with                  #
# NOTE: You can find the latitude and longitude of a location at https://www.latlong.net/                            #
Latitude: '0'
Longitude: '0'
#                                                                                                                    #
######################################################################################################################

# Set to true for various console messages when time and weather sync are executed
# This is useful if the plugin is not working, and you want to find out what's wrong
# This will also provide java error messages when an error is caught and managed by RTM
# Note: There will be no messages during a time sync because they happen very frequently
# Note: Unhandled plugin errors will still be logged regardless of the debug value
Debug: false
