# RealTimeWeather Configuration File (v1)
# Configure RTM below BEFORE using it

################################# TIME SYNC SETTINGS #################################################################
# Set to true to enable time syncing, or false to disable                                                            #
SyncTime: false
#
# You can change the time between time syncs from the default (5 seconds) below                                      #
TimeSyncInterval: 100
#                                                                                                                    #
# Enter the time zone that you want to sync your world(s) with                                                       #
# This location CAN be different from your chosen weather location                                                   #
# You can find a full list of timezones here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List      #
Timezone: 'America/New_York'
#                                                                                                                    #
######################################################################################################################

################################# WEATHER SYNC SETTINGS ##############################################################
# Set to true to enable weather syncing, or false to disable                                                         #
SyncWeather: false
#
# You can change the time between weather syncs from the default (5 minutes) below                                   #
# Due to OpenWeather's restrictions, setting this value below 2400 (2 minutes) will cause problems                   #
# You can find a handy tick calculator here: https://mapmaking.fr/tick/                                              #
WeatherSyncInterval: 6000
#                                                                                                                    #
# In order to access the weather sync feature, create an account at https://openweathermap.org/                      #
# Then, create an API key at https://openweathermap.org/appid and copy it                                            #
# Finally, paste the API key below and DO NOT SHARE IT WITH OTHERS                                                   #
APIKey: 'API_KEY'
# Enter the zip code and country code of the location that you want to sync your world(s) weather with               #
# NOTE: A list of country codes can be found at https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes               #
ZipCode: '10001'
CountryCode: 'US'
#                                                                                                                    #
######################################################################################################################

# Set to true for various console messages when time and weather sync are executed
# This is useful if the plugin is not working, and you want to find out what's wrong
# This will also provide java error messages when an error is caught and managed by RTM
# Note: There will be no messages during a time sync because they happen every second
# Note: Java exceptions and fatal plugin errors will still be logged regardless of the debug value
Debug: false
