name: RealTimeWeather
version: '${version}'
main: io.github.jack1424.realtimeweather.RealTimeWeather
description: Sync your Minecraft server's time and weather with the real world
author: Jack1424
load: POSTWORLD
website: https://github.com/Jack1424/RealTimeWeather
api-version: '1.21.5'
folia-supported: true